version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/pipeline_project/static/uploads
      - ./instance:/pipeline_project/instance
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
